#!/usr/bin/env bash
# Writes src/xrCore/Debug/xrSentry_embed.h from SENTRY_DSN (e.g. secrets.SENTRY_DSN in GitHub Actions).
# Escapes \ and " for a C string literal. Empty SENTRY_DSN -> empty embedded string.
set -euo pipefail

REPO_ROOT="${GITHUB_WORKSPACE:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
TARGET="${REPO_ROOT}/src/xrCore/Debug/xrSentry_embed.h"
DSN="${SENTRY_DSN:-}"

escaped=$(printf '%s' "$DSN" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')

mkdir -p "$(dirname "$TARGET")"

{
  printf '%s\n' \
    '#pragma once' \
    '' \
    '// Generated by misc/ci/write_xr_sentry_embed.sh (CI: secrets.SENTRY_DSN).' \
    '// Committed default in git is overwritten here. Runtime SENTRY_DSN env still overrides in xrSentry.cpp.' \
    ''
  printf '%s\n' "#define XRAY_SENTRY_DEFAULT_DSN_STR \"${escaped}\""
} > "$TARGET"

echo "Updated ${TARGET} (embedded DSN length: ${#DSN})"
